sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tonyduong1112/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tonyduong1112/react-test npm test

after_success:
  - docker build -t tonyduong1112/multi-client ./client
  - docker build -t tonyduong1112/multi-nginx ./nginx
  - docker build -t tonyduong1112/multi-server ./server
  - docker build -t tonyduong1112/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tonyduong1112/multi-client
  - docker push tonyduong1112/multi-nginx
  - docker push tonyduong1112/multi-server
  - docker push tonyduong1112/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
    bucket_path: 'docker-multi'
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
